// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/film_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 3224674830285237766),
      name: 'FilmModel',
      lastPropertyId: const IdUid(4, 3345951828331713971),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1479491376299469921),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5880191916134710134),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1939964798704320206),
            name: 'year',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3345951828331713971),
            name: 'country',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3224674830285237766),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [1857502263759276772],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        5352659210077781708,
        3587723556331613560,
        6752721877032709783,
        9118725565339612470,
        6252589777666970914
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    FilmModel: EntityDefinition<FilmModel>(
        model: _entities[0],
        toOneRelations: (FilmModel object) => [],
        toManyRelations: (FilmModel object) => {},
        getId: (FilmModel object) => object.id,
        setId: (FilmModel object, int id) {
          object.id = id;
        },
        objectToFB: (FilmModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final yearOffset = fbb.writeString(object.year);
          final countryOffset = fbb.writeString(object.country);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, yearOffset);
          fbb.addOffset(3, countryOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final yearParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final countryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = FilmModel(
              id: idParam,
              title: titleParam,
              year: yearParam,
              country: countryParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [FilmModel] entity fields to define ObjectBox queries.
class FilmModel_ {
  /// see [FilmModel.id]
  static final id = QueryIntegerProperty<FilmModel>(_entities[0].properties[0]);

  /// see [FilmModel.title]
  static final title =
      QueryStringProperty<FilmModel>(_entities[0].properties[1]);

  /// see [FilmModel.year]
  static final year =
      QueryStringProperty<FilmModel>(_entities[0].properties[2]);

  /// see [FilmModel.country]
  static final country =
      QueryStringProperty<FilmModel>(_entities[0].properties[3]);
}
